const CREATE_SPENDINGS_TABLE = "CREATE TABLE IF NOT EXISTS spending (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `for` TEXT, `category` TEXT, `sum` TEXT, `currency` TEXT, `when` TEXT, `label` TEXT)";
const CREATE_LABEL_TABLE = "CREATE TABLE IF NOT EXISTS labels(`id` INTEGER PRIMARY KEY AUTOINCREMENT, `label` TEXT)";
const CREATE_LABEL_TO_SPENDING_TABLE = "CREATE TABLE IF NOT EXISTS labels(`id` INTEGER PRIMARY KEY AUTOINCREMENT, `label_id` INTEGER, `spending_id` INTEGER)";



module.exports = {
    CREATE_SPENDINGS_TABLE: CREATE_SPENDINGS_TABLE,
    CREATE_LABEL_TABLE: CREATE_LABEL_TABLE,
    CREATE_LABEL_TO_SPENDING_TABLE: CREATE_LABEL_TO_SPENDING_TABLE,

}